---
- name: Deploy containers on HTPiC host
  hosts: htpic

  tasks:
    - name: Create portainer_data volume
      become: yes
      file:
        path: /var/lib/docker/volumes/portainer_data
        state: directory
        mode: '0755'
    
    - name: Deploy portainer
      become_user: pi
      docker_container:
        name: portainer
        image: portainer/portainer
        state: started
        recreate: yes
        restart_policy: always
        ports:
          - "9000:9000"
        volumes:
          - "/var/run/docker.sock:/var/run/docker.sock"
          - "/var/lib/docker/volumes/portainer_data:/data"
        env:
          TZ: "America/New_York"
          
    - name: Create heimdall volume
      become: yes
      file:
        path: /var/lib/docker/volumes/heimdall
        state: directory
        mode: '0755'
          
    - name: Deploy heimdall
      become_user: pi
      docker_container:
        name: heimdall
        hostname: heimdall
        image: linuxserver/heimdall
        recreate: yes
        restart_policy: always
        ports:
          - "444:443"
          - "81:80"
        volumes:
          - "/var/lib/docker/volumes/heimdall:/config"
        env:
          TZ: "America/New_York"
          PUID: "1000"
          PGID: "1000"
          
    - name: Deploy radarr
      become_user: pi
      docker_container:
        name: transmission-vpn-radarr
        hostname: transmission-vpn-radarr
        image: haugene/transmission-openvpn
        recreate: yes
        restart_policy: always
        capabilities:
          - NET_ADMIN
        devices:
          - /dev/net/tun
        ports:
          - "9091:9091"
        dns_servers:
          - "1.1.1.1"
          - "1.0.0.1"
        volumes:
          - "/volume1/docker/transmission-vpn-radarr:/data
          - "/volume1/docker/shared:/shared
          - "/volume1/Downloads:/data/watch
          - "/volume1/Downloads/completed:/data/completed
          - "/volume1/Downloads/incomplete:/data/incomplete
        env:
          - OPENVPN_PROVIDER=PIA
          - OPENVPN_USERNAME=username
          - OPENVPN_PASSWORD=password
          - OPENVPN_CONFIG=AUTO
          - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
          - LOCAL_NETWORK=192.168.1.0/24
          - PUID=1030
          - PGID=101
          - TZ="America/New_York"
          - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=false
          - TRANSMISSION_RPC_HOST_WHITELIST="127.0.0.1,192.168.*.*"
          - TRANSMISSION_RPC_PASSWORD=
          - TRANSMISSION_RPC_USERNAME=
          - TRANSMISSION_UMASK=002
          - TRANSMISSION_RATIO_LIMIT=1.00
          - TRANSMISSION_RATIO_LIMIT_ENABLED=true
          - TRANSMISSION_DOWNLOAD_LIMIT_ENABLED=0
          - TRANSMISSION_DOWNLOAD_QUEUE_ENABLED=false
          - TRANSMISSION_DOWNLOAD_QUEUE_SIZE=999
          - TRANSMISSION_IDLE_SEEDING_LIMIT_ENABLED=false
          - TRANSMISSION_MAX_PEERS_GLOBAL=999
          - TRANSMISSION_PEER_LIMIT_GLOBAL=999
          - TRANSMISSION_PEER_LIMIT_PER_TORRENT=999      
          - TRANSMISSION_SEED_QUEUE_ENABLED=false     
          - TRANSMISSION_SPEED_LIMIT_DOWN_ENABLED=false      
          - TRANSMISSION_SPEED_LIMIT_UP_ENABLED=true
          - TRANSMISSION_SPEED_LIMIT_UP=1
          - TRANSMISSION_START_ADDED_TORRENTS=true
          - TRANSMISSION_TRASH_ORIGINAL_TORRENT_FILES=false
...
